### ISSUE TITLE
required attribute not supported

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-autocomplete#3]
This component does not seem to support the required attribute and does not stop form validation if nothing has been added or entered.

Example element:
`<form id="formID"><cosmoz-autocomplete id="ID" multi-selection class="flex" search-type="[[ _('Example', t) ]]" value-property="name" placeholder="[[ _('Select example', t) ]]" selected-items="{{ exampleItemsSelected }}" items="{{ exampleItemsAvailable }}" required></cosmoz-autocomplete></form>`

Example JS:
```
if (!this.$.FormID.checkValidity()) {
	// should go here when empty
	this.$.FormID.reportValidity();
	return;
}
// but goes here instead
```

**Comment by teslor** [comment]
checkValidity() works only if original Input element has "required" attribute.
To ensure this I added mapping for "required" attribute to paper-input inside cosmoz-autocomplete.
However checkValidity() only does simple validation.
To use custom validation validate() method should be used on the element or iron-form.

**Comment by plequang** [comment]
Yes you're right.
Actually since this issue was reported, @dotpointer implemented `iron-validatable-behavior` for this element and, as you suggest,  we are using `<iron-form>.validate` to perfom validation.

**Comment by plequang** [comment]
Fixed by @dotpointer (implementing `iron-validatable-behavior1`) and @teslor in #11
