### ISSUE TITLE
Detect right-side boundaries and switch to right-align

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-autocomplete#69]
![image](https://user-images.githubusercontent.com/960553/93304621-94980a00-f7fd-11ea-9330-00dc4740b363.png)

Currently the width of the suggestions can exceed the available space, effectively cutting the labels off.
We should be able to detect this overflow and adjust to aligning the suggestions drop-down to the right instead.
(Or just do it when the middle of the input is on the right side of the screen..)

**Comment by megheaiulian** [comment]
To fix this we should use a portal for suggestions and something like https://www.npmjs.com/package/position.js to position the elements.
