### ISSUE TITLE
Handle dot path `path.subpath` in textProperty

### ISSUE THREAD

**Issue by megheaiulian** [Neovici/cosmoz-autocomplete#72]
Handle dot path `path.subpath` in textProperty

**Comment by JockeCK** [comment]
related: https://github.com/Neovici/cosmoz-frontend/issues/2881

**Comment by nomego** [comment]
If  Neovici/cosmoz-frontend#2881 is the reason behind this issue we should reject it.

**Comment by JockeCK** [comment]
closing
