### ISSUE TITLE
Behavior not found warning

### ISSUE THREAD

**Issue by teslor** [Neovici/cosmoz-autocomplete#8]
I get a warning "Behavior Polymer.IronFormElementBehavior not found when mixing properties into cosmoz-autocomplete!" when viewing page http://127.0.0.1:8081/components/cosmoz-autocomplete/ in the browser (using polymer serve).
The warning is shown always for the latest behavior in Behaviors array, looks like a bug in hydrolysis - analysis tool for polymer. The component itself (in demo) seems to work ok.

**Comment by plequang** [comment]
I think this is because we separate .html and .js files, and hydrolysis (aka polymer analyzer) does not handle that correctly.
See https://github.com/Polymer/polymer-analyzer/issues/509

**Comment by teslor** [comment]
Just tried to place the component code in html file, the warning still appears. Maybe it's because cosmoz behaviors components are also in separate files, not sure.

**Comment by plequang** [comment]
Yes I think you're right. 
We need to discuss internally a rewrite of cosmoz behaviors in a single .html file
Will keep this issue open until we decide what we do.

**Comment by nomego** [comment]
cosmoz-behaviors
